font_family jetbrains mono nerd font

font_size 14.0

background_opacity 0.85

# launch fastfetch --disk-show-subvolumes 1 --kitty /home/linus/圖片/106367889_p0.png --logo-width 27 

# include ~/.cache/wal/colors-kitty.conf
include ./arcade.conf
