# Nord Colorscheme for Kitty
# Based on:
# - https://gist.github.com/marcusramberg/64010234c95a93d953e8c79fdaf94192
# - https://github.com/arcticicestudio/nord-hyper

foreground            #bbc2cf
background            #282c34
selection_foreground  #000000
selection_background  #FFFACD
url_color             #0087BD
cursor                #81A1C1

# black
color0   #282c34
color8   #4C566A

# red
color1   #ff6c6b
color9   #BF616A

# green
color2   #98be65
color10  #A3BE8C

# yellow
color3   #ecbe7b
color11  #EBCB8B

# blue
color4  #51afef
color12 #81A1C1

# magenta
color5   #c678dd
color13  #B48EAD

# cyan
color6   #46d9ff
color14  #8FBCBB

# white
color7   #bbc2cf
color15  #ECEFF4
